name: Terraform-AI-Review-Agent

on:
  pull_request:
    paths: "terraform-review-agent/**"

jobs:
  terraform-ai-review:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout the Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: Install Terrascan
        run: |
          curl -L https://github.com/tenable/terrascan/releases/download/v1.18.3/terrascan_1.18.3_Linux_x86_64.tar.gz \
            | tar -xz
          sudo mv terrascan /usr/local/bin/
          terrascan version

      - name: Terrascan Init
        run: terrascan init

      - name: Run Terrascan (Terraform directory scan)
        run: |
          set +e
          terrascan scan \
            -i terraform \
            -d terraform-review-agent/terraform \
            -t aws \
            -o json \
            --log-level error \
            > terrascan_report.json
          set -e

      - name: Upload Terrascan Report
        uses: actions/upload-artifact@v4
        with:
          name: terrascan-report
          path: terrascan_report.json  

      - name: Invoke Terraform AI Review Lambda
        id: ai_review
        run: |
          aws lambda invoke \
            --function-name terraform-ai-review-agent \
            --cli-binary-format raw-in-base64-out \
            --payload file://terrascan_report.json \
            response.json
          jq -r '.ai_review' response.json

      - name: Fail PR if AI rejects
        run: |
          VERDICT=$(jq -r '.verdict' response.json)

          echo "üß† AI Verdict: $VERDICT"

          if [[ "$VERDICT" == "REJECT" ]]; then
            echo "‚ùå AI Agent rejected Terraform changes"
            exit 1
          else
            echo "‚úÖ AI Agent approved (or approved with changes)"
          fi